#!/bin/bash
# Script to get Supabase Service Role Key
# Run this script and follow the instructions to get your service role key

echo "🔧 Getting Supabase Service Role Key"
echo "=================================="
echo ""
echo "To get your Supabase Service Role Key:"
echo ""
echo "1. Go to your Supabase Dashboard:"
echo "   https://supabase.com/dashboard/project/weckxacnhzuzuvjvdyvj"
echo ""
echo "2. Navigate to: Settings > API"
echo ""
echo "3. Find the 'service_role' key (NOT the 'anon' key)"
echo "   - It should start with: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
echo "   - This key has admin privileges and should be kept secret"
echo ""
echo "4. Copy the service_role key and paste it into your .env.local file:"
echo "   Replace 'YOUR_SERVICE_ROLE_KEY_HERE' with your actual service role key"
echo ""
echo "5. Restart your development server after updating .env.local"
echo ""
echo "⚠️  IMPORTANT: Never expose the service_role key in client-side code!"
echo "   Only use it in server-side API routes."
echo ""
echo "Current .env.local location: $(pwd)/.env.local"
echo ""
echo "After adding the key, your .env.local should look like:"
echo "SUPABASE_SERVICE_ROLE_KEY=\"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ...your-actual-key\""