#!/bin/bash

# This script will help you update your DATABASE_URL with the correct Supabase connection string

echo "🔧 Fixing Database Connection"
echo "=============================="
echo ""
echo "You need to get your Supabase DATABASE_URL:"
echo ""
echo "1. Go to: https://app.supabase.com/project/weckxacnhzuzuvjvdyvj/settings/database"
echo ""
echo "2. Scroll to 'Connection string' section"
echo ""
echo "3. Select 'URI' tab"
echo ""
echo "4. Copy the connection string (it will look like):"
echo "   postgresql://postgres.[YOUR-PROJECT-REF]:[YOUR-PASSWORD]@aws-0-us-west-1.pooler.supabase.com:6543/postgres"
echo ""
echo "5. Replace [YOUR-PASSWORD] with your database password"
echo ""
echo "6. Then run:"
echo "   echo 'DATABASE_URL=\"your-connection-string-here\"' >> .env"
echo ""
echo "Or manually edit .env file and replace DATABASE_URL line"
echo ""
echo "After updating, run:"
echo "  npx prisma generate"
echo "  npx prisma db push"
echo "  npm run dev"
